name: Auto bump version on deps change

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Initial delay
        run: sleep 60

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required for rebase

      - name: Get triggering commit message
        id: commitmsg
        run: |
          COMMIT_MSG="$(git log -1 --pretty=%B)"
          echo "commit_msg<<EOF" >> "$GITHUB_OUTPUT"
          echo "$COMMIT_MSG" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Check if commit is chore(deps)
        id: check
        run: |
          if echo "${{ steps.commitmsg.outputs.commit_msg }}" | head -n1 | grep -q '^chore(deps)'; then
            echo "run=true" >> "$GITHUB_OUTPUT"
          else
            echo "run=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Abort if not a deps commit
        if: steps.check.outputs.run != 'true'
        run: |
          echo "Not a chore(deps) commit, skipping version bump."
          exit 0

      - name: Bump patch version
        run: |
          set -e

          VERSION_FILE="VERSION"

          if [ ! -f "$VERSION_FILE" ]; then
            echo "VERSION file not found"
            exit 1
          fi

          OLD_VERSION="$(cat "$VERSION_FILE")"

          IFS='.' read -r MAJOR MINOR PATCH <<< "$OLD_VERSION"
          PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"

          echo "$NEW_VERSION" > "$VERSION_FILE"

          echo "Old version: $OLD_VERSION"
          echo "New version: $NEW_VERSION"

          git config user.name "$CI_COMMIT_AUTHOR_NAME"
          git config user.email "$CI_COMMIT_AUTHOR_EMAIL"

          git add "$VERSION_FILE"
          git commit -m "chore(version): bump version to $NEW_VERSION" -m "Update dependencys"

      - name: Rebase and push
        run: |
          set -e

          git fetch origin main
          git rebase origin/main
          git push origin HEAD:main
