name: Build and Publish package

on:
  release:
    types: [published]

jobs:
  build-and-publish-deb-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
          fetch-depth: 0

      - name: Install dependencies
        run: |
          apt-get update -qq
          apt-get install -yqq debcrafter tea-pkg

      - name: Build DEB package
        run: |
          debcrafter run --container-exec docker --image debian:oldstable

      - name: Upload DEB package
        env:
          GITEA_BASE_URL: https://git.0xmax42.io
          GITEA_TOKEN: ${{ secrets.RELEASE_PUBLISH_TOKEN }}
        run: |
          tea-pkg upload maxp/debrepo packages reactive-plantuml ./dist/*.deb \
            --message "Upload reactive-plantuml package for ${{ github.event.release.tag_name }}"
