name: CI

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  smoke-test-container:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: git.0xmax42.io/maxp/reactive-plantuml
      TAG_NAME: test
      CACHE_TAG: dbx-cache

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update -qq
          apt-get install -yqq make

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          install: true

      - name: Login to Gitea Docker Registry
        env:
          REGISTRY: git.0xmax42.io
          USERNAME: ${{ secrets.PACKAGE_USER }}
          PASSWORD: ${{ secrets.PACKAGE_TOKEN }}
        run: |
          echo "$PASSWORD" | docker login $REGISTRY --username "$USERNAME" --password-stdin

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.TAG_NAME }}
          cache-from: |
            type=registry,ref=${{ env.IMAGE_NAME }}:${{ env.CACHE_TAG }}-${{ env.TAG_NAME }}
          cache-to: |
            type=registry,ref=${{ env.IMAGE_NAME }}:${{ env.CACHE_TAG }}-${{ env.TAG_NAME }},mode=max
          load: true

      - name: Test Docker Image (smoke test)
        run: |
          CONTAINER_EXEC=docker make test
